language: node_js
node_js: node
addons:
  chrome: stable
script:
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:ci || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test || travis_terminate 1;
  fi
env:
  global:
  - SAUCE_USERNAME: team_mango
  # SAUCE_ACCESS_KEY
  - secure: v0BAcmjKsVX8E7WgsXArobu6FhG1BceHowvZEmLWn16movyW4nDK8l6Klru0J5TH4gqelFO4nscy9nN/F+BbfOf6L3P8EGhNCIM27ks7Y1+mPSvm4Nrv8ksSIPTmgR0+qstcuDXDGKwknEMqpS1RfuO6K8SDkOZ9EF7zwKgEaeGfM3SV0vJj+pH6MP7MKyq+HSMflId0U9wY2AibNIoY/86nVurCcZN8MPC3GHIR4gE30o15i0c6NzVBhCr4YeljvWd9lly5wZCyDqgzpMayL+BCrVUEmKyxgv+gmyQyyik2MYbMaTOYGNQ44b13Qutyh5j4iN+PknlF4D0dvGNQL9Pf/Rri3CX/qUoB0qk3VFydvYkjXJG1DBnfQCK+juJNfCLrnE5I8DrTkLZpJSUvCvExNo9ywF1KI9n1nQaOOwvDlSWksC1XJkCPZGkrGdSMVHHvKIR3/bg95wE9Fah3qnvN4teABLPIU6egFSBBDfFzTVGtOQTTDGPe82zkqjUHQmgKGQbwFZpfDVgLk8M6fqX8wQwDzgxpaxruHnGYurZlccPTSXob6HYBGez/wuhhIZA/XoMmJZNwtg+fJ/FiLkmj2cljmjYZETQcbVef6CsDSO6d3RulW8g6Dt0suv7MA+TepaX/l+Zh6P98vEQy6Sqfflu/H2chQyxz1ORAz+w=
