name: CI
on: pull_request
permissions:
  contents: read
jobs:
  lint:
    name: Lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Set up node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: |
          npm install
          npm install @web/test-runner-playwright --no-save
          npx playwright install-deps
      - name: Lint (JavaScript)
        run: npm run lint
      - name: Unit Tests (cross-browser)
        run: npx web-test-runner --files "./test/**/*.test.js" --node-resolve --playwright --browsers chromium firefox webkit
