name: Release
on:
  push:
    branches:
      - master
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
permissions:
  contents: read
concurrency: release
jobs:
  release:
    if: (!contains(github.event.head_commit.message, 'skip ci'))
    name: Release
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Semantic Release
        uses: BrightspaceUI/actions/semantic-release@main
        with:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{secrets.D2L_GITHUB_TOKEN}}
