name: Release
on:
  push:
    branches:
      - main
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
env:
  FORCE_COLOR: 3
permissions:
  contents: read
concurrency: release
jobs:
  release:
    name: Release
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Set up node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
      - name: Semantic Release
        uses: BrightspaceUI/actions/semantic-release@main
        with:
          GITHUB_TOKEN: ${{secrets.D2L_GITHUB_TOKEN}}
          MINOR_RELEASE_WITH_LMS: true
          NPM: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          RALLY_API_KEY: ${{secrets.RALLY_API_KEY}}
